# build an executable name convert_float_to_bits from convert_float_to_bits.c
all: convert_float_to_bits.c
	gcc -g -Wall -o convert_float_to_bits convert_float_to_bits.c

clean:
	$(RM) convert_float_to_bits
	$(RM) output.txt

